import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Director Jmills</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to Jmills Director</h1>

        <p>
          Get started by editing <code>pages/index.js</code>
        </p>
      </main>

      <footer>Footer</footer>
    </div>
  );
}
